apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-exercise 
  namespace: test
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command:
                - sleep 
                - "300"
          restartPolicy: OnFailure
          